name: deploy frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: lint the code
        run: npm run lint
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/static
      - name: build the code
        run: npm run build

  deploy:
    needs: build
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: format the code
        run: npm run lint
      - name: install aws CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-north-1
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
            path: dist/static
      - name: deploy to s3
        run: aws s3 sync dist/static s3://${{secrets.AWS_CONTENT_S3_BUCKET}}
